// ============================================================
//  data.js — 只需编辑这个文件来更新网站内容
// ============================================================

const SITE_DATA = {

  meta: {
    groupName: "NEXUS",
    tagline: "Mod 列表 · 版本信息 · 下载链接 · 玩法提案",
    githubUrl: "https://github.com/tyxo0o315",
    // 腾讯文档「一起玩想法」共享文档链接，留空则隐藏嵌入区域
    ideasDocUrl: "https://docs.qq.com/doc/DZEJrdkhGcmhianZo",
  },

  // ── 当前游戏 ──────────────────────────────────────────────
  activeGames: [
    {
      id: "mc-survival",
      title: "Minecraft",
      subtitle: "Java 版生存",
      version: "1.21.4",
      loader: "Fabric",
      loaderVersion: "0.19.2",
      totalMods: 25,
      status: "active",
      lastUpdated: "2026-05-27",
      packDownloadUrl: "https://github.com/tyxo0o315/nexus-gamesite/releases/download/v1.0.0/nexus-mods-1.21.4.zip",
      packFileName: "nexus-mods-1.21.4.zip",
      serverAddress: "frp-use.com:29702",
      coverEmoji: "⛏️",
      notes: "用 PCL 启动，需要 Java 21，安装 Fabric 加载器 0.19.2。",
    },
  ],

  // ── Mod 列表 ───────────────────────────────────────────────
  mods: [
    // 性能优化
    {
      id: "sodium",
      name: "Sodium",
      category: "性能优化",
      description: "渲染引擎替换，大幅提升帧率。",
      version: "0.6.13",
      required: true,
      downloadUrl: "https://modrinth.com/mod/sodium",
    },
    {
      id: "sodium-extra",
      name: "Sodium Extra",
      category: "性能优化",
      description: "Sodium 扩展设置面板，提供更多视觉/性能选项。",
      version: "0.6.1",
      required: false,
      downloadUrl: "https://modrinth.com/mod/sodium-extra",
    },
    {
      id: "ferritecore",
      name: "FerriteCore",
      category: "性能优化",
      description: "大幅降低内存占用，加载大型存档不再卡顿。",
      version: "7.1.3",
      required: true,
      downloadUrl: "https://modrinth.com/mod/ferrite-core",
    },
    {
      id: "entityculling",
      name: "Entity Culling",
      category: "性能优化",
      description: "异步剔除不可见实体的渲染，密集场景帧率显著提升。",
      version: "1.10.2",
      required: false,
      downloadUrl: "https://modrinth.com/mod/entityculling",
    },
    {
      id: "dynamic-fps",
      name: "Dynamic FPS",
      category: "性能优化",
      description: "游戏在后台/最小化时自动降低帧率，节省资源。",
      version: "3.11.4",
      required: false,
      downloadUrl: "https://modrinth.com/mod/dynamic-fps",
    },
    // 视觉效果
    {
      id: "iris",
      name: "Iris Shaders",
      category: "视觉效果",
      description: "光影包支持，兼容绝大多数 OptiFine 光影。",
      version: "1.8.8",
      required: false,
      downloadUrl: "https://modrinth.com/mod/iris",
    },
    {
      id: "lambdynamiclights",
      name: "LambDynamicLights",
      category: "视觉效果",
      description: "手持发光物品（火把、萤火虫瓶等）动态照亮周围环境。",
      version: "4.1.3",
      required: false,
      downloadUrl: "https://modrinth.com/mod/lambdynamiclights",
    },
    // 地图
    {
      id: "xaeros-minimap",
      name: "Xaero's Minimap",
      category: "地图",
      description: "右上角小地图，记录实体位置、死亡点，探索必备。",
      version: "25.3.12",
      required: false,
      downloadUrl: "https://modrinth.com/mod/xaeros-minimap",
    },
    {
      id: "xaeros-worldmap",
      name: "Xaero's World Map",
      category: "地图",
      description: "全屏世界地图（M 键打开），配合小地图食用效果最佳。",
      version: "1.40.16",
      required: false,
      downloadUrl: "https://modrinth.com/mod/xaeros-world-map",
    },
    // 工具
    {
      id: "rei",
      name: "REI（合成表查询）",
      category: "工具",
      description: "查询所有物品合成配方和用途，再也不用开 Wiki。",
      version: "18.0.808",
      required: true,
      downloadUrl: "https://modrinth.com/mod/rei",
    },
    {
      id: "jade",
      name: "Jade",
      category: "工具",
      description: "准星指向方块/实体时显示详细信息提示。",
      version: "17.2.2",
      required: false,
      downloadUrl: "https://modrinth.com/mod/jade",
    },
    {
      id: "appleskin",
      name: "AppleSkin",
      category: "工具",
      description: "显示精确的饥饿值与饱和度，告别盲目吃东西。",
      version: "3.0.6",
      required: false,
      downloadUrl: "https://modrinth.com/mod/appleskin",
    },
    {
      id: "betterf3",
      name: "BetterF3",
      category: "工具",
      description: "F3 调试界面重设计，信息分色分组更易读。",
      version: "13.0.0",
      required: false,
      downloadUrl: "https://modrinth.com/mod/betterf3",
    },
    {
      id: "litematica",
      name: "Litematica（投影）",
      category: "工具",
      description: "加载建筑原理图投影，对着幽灵轮廓搭建不出错。",
      version: "0.21.6",
      required: false,
      downloadUrl: "https://modrinth.com/mod/litematica",
    },
    {
      id: "axiom",
      name: "Axiom",
      category: "工具",
      description: "高级创意模式建筑工具，支持笔刷、替换、3D 选区等操作。",
      version: "5.4.2",
      required: false,
      downloadUrl: "https://modrinth.com/mod/axiom",
    },
    {
      id: "customskinloader",
      name: "Custom Skin Loader",
      category: "工具",
      description: "支持从自定义皮肤站加载皮肤，离线/正版均可用。",
      version: "14.28",
      required: false,
      downloadUrl: "https://github.com/xfl03/MCCustomSkinLoader",
    },
    {
      id: "lanserverproperties",
      name: "LAN Server Properties",
      category: "工具",
      description: "局域网联机时可自定义端口、游戏模式等服务器参数。",
      version: "1.13.2",
      required: false,
      downloadUrl: "https://modrinth.com/mod/lan-server-properties",
    },
    // 依赖库
    {
      id: "fabric-api",
      name: "Fabric API",
      category: "依赖库",
      description: "Fabric 模组的核心 API，绝大多数模组的必要前置。",
      version: "0.119.4",
      required: true,
      downloadUrl: "https://modrinth.com/mod/fabric-api",
    },
    {
      id: "architectury",
      name: "Architectury API",
      category: "依赖库",
      description: "跨平台模组开发框架，部分模组的前置依赖。",
      version: "15.0.3",
      required: true,
      downloadUrl: "https://modrinth.com/mod/architectury-api",
    },
    {
      id: "cloth-config",
      name: "Cloth Config",
      category: "依赖库",
      description: "模组配置界面库，为多个模组提供设置页面支持。",
      version: "17.0.144",
      required: true,
      downloadUrl: "https://modrinth.com/mod/cloth-config",
    },
    {
      id: "fabric-language-kotlin",
      name: "Fabric Language Kotlin",
      category: "依赖库",
      description: "Kotlin 语言运行时支持，部分模组需要。",
      version: "1.13.11",
      required: true,
      downloadUrl: "https://modrinth.com/mod/fabric-language-kotlin",
    },
    {
      id: "forge-config-api-port",
      name: "Forge Config API Port",
      category: "依赖库",
      description: "将 Forge 配置 API 移植到 Fabric，部分模组需要。",
      version: "v21.4.3",
      required: true,
      downloadUrl: "https://modrinth.com/mod/forge-config-api-port",
    },
    {
      id: "libipn",
      name: "libIPN",
      category: "依赖库",
      description: "背包相关模组的共享库。",
      version: "6.5.1",
      required: true,
      downloadUrl: "https://modrinth.com/mod/libipn",
    },
    {
      id: "malilib",
      name: "MaLiLib",
      category: "依赖库",
      description: "Masa 系列模组（Litematica、MiniHUD 等）的共享前置库。",
      version: "0.23.5",
      required: true,
      downloadUrl: "https://modrinth.com/mod/malilib",
    },
    {
      id: "searchables",
      name: "Searchables",
      category: "依赖库",
      description: "为 REI 等模组提供搜索功能支持的工具库。",
      version: "1.0.5",
      required: true,
      downloadUrl: "https://modrinth.com/mod/searchables",
    },
  ],

  modCategories: [
    { id: "all",    label: "全部" },
    { id: "性能优化", label: "性能优化" },
    { id: "视觉效果", label: "视觉效果" },
    { id: "地图",   label: "地图" },
    { id: "工具",   label: "工具" },
    { id: "依赖库", label: "依赖库" },
  ],

  // ── 一起玩的想法 ───────────────────────────────────────────
  playingIdeas: [
    {
      id: "idea-1",
      author: "Alex",
      title: "硬核周末挑战",
      body: "周五晚上一起开新档，单命不开作弊，看谁撑得最久。死了就只能观战帮出主意。",
      tags: ["硬核", "Minecraft"],
      votes: 5,
      pinned: true,
      color: "cream",
      date: "2026-05-22",
    },
    {
      id: "idea-2",
      author: "Sam",
      title: "再打一局 Lethal",
      body: "新月球出了，听说里面全是狗头人。周末有人吗？",
      tags: ["Lethal", "恐怖"],
      votes: 4,
      pinned: false,
      color: "warm",
      date: "2026-05-20",
    },
    {
      id: "idea-3",
      author: "MiMi",
      title: "建造竞赛",
      body: "主题：「水下城市」，每人一块 100×100 的地，48 小时后大家一起投票评分，输的人负责下次的服务器费用。",
      tags: ["建造", "Minecraft"],
      votes: 7,
      pinned: false,
      color: "sage",
      date: "2026-05-18",
    },
    {
      id: "idea-4",
      author: "Kris",
      title: "全力冲 The End",
      body: "这把生存档开了两个月了还没打龙，找个周末一起冲，顺便把末地城都搜刮一遍。",
      tags: ["Minecraft", "PVE"],
      votes: 6,
      pinned: false,
      color: "cream",
      date: "2026-05-15",
    },
    {
      id: "idea-5",
      author: "Alex",
      title: "整一个自动农场",
      body: "想搞一个全自动的铁矿石→铁锭流水线，一起来设计蓝图？我已经研究了两天机械结构了。",
      tags: ["建造", "工程"],
      votes: 3,
      pinned: false,
      color: "warm",
      date: "2026-05-10",
    },
  ],
};
